version: "3"

services:
  jupyter:
    #user: "${UID}:${GID}"
    #user: 1000:1000
    image: jupyter:latest
    hostname: jupyter
    privileged: true
    build: .
    environment:
      - PULSE_SERVER=${PULSE_SERVER}
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native 
      - /home/brad:/home/ubuntu
    devices:
      - '/dev/snd:/dev/snd'
    network_mode: host
